### ISSUE TITLE
Add aar to Maven Central

### ISSUE THREAD

**Issue by Wavesonics** [ragunathjawahar/simple-section-adapter#3]
It would be useful to get this library as an AAR (_or possibly only a JAR would be necessary_) and submitted to Maven Central.

**Comment by ragunathjawahar** [comment]
Hi, the adapter is now a part of the [Adapter Kit](https://github.com/mobsandgeeks/adapter-kit) project and is already available on maven central.

**Comment by Wavesonics** [comment]
Oh awesome, good to know!

**Comment by ragunathjawahar** [comment]
@Wavesonics You're welcome :)
